package model.POJO;
// Generated 02.Oca.2015 16:58:18 by Hibernate Tools 4.3.1



/**
 * Destek generated by hbm2java
 */
public class Destek  implements java.io.Serializable {


     private Integer destekId;
     private User user;

    public Destek() {
    }

    public Destek(User user) {
       this.user = user;
    }
   
    public Integer getDestekId() {
        return this.destekId;
    }
    
    public void setDestekId(Integer destekId) {
        this.destekId = destekId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


