package model.POJO;
// Generated 02.Oca.2015 16:58:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Kategori generated by hbm2java
 */
public class Kategori  implements java.io.Serializable {


     private Integer kategoriId;
     private String kategoriAdi;
     private Set uruns = new HashSet(0);

    public Kategori() {
    }

	
    public Kategori(String kategoriAdi) {
        this.kategoriAdi = kategoriAdi;
    }
    public Kategori(String kategoriAdi, Set uruns) {
       this.kategoriAdi = kategoriAdi;
       this.uruns = uruns;
    }
   
    public Integer getKategoriId() {
        return this.kategoriId;
    }
    
    public void setKategoriId(Integer kategoriId) {
        this.kategoriId = kategoriId;
    }
    public String getKategoriAdi() {
        return this.kategoriAdi;
    }
    
    public void setKategoriAdi(String kategoriAdi) {
        this.kategoriAdi = kategoriAdi;
    }
    public Set getUruns() {
        return this.uruns;
    }
    
    public void setUruns(Set uruns) {
        this.uruns = uruns;
    }




}


