package model.POJO;
// Generated 02.Oca.2015 16:58:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Musteri generated by hbm2java
 */
public class Musteri  implements java.io.Serializable {


     private Integer musteriId;
     private long musteriTc;
     private String musteriAd;
     private String musteriSoyad;
     private String musteriMail;
     private long musteriTel;
     private String musteriAdres;
     private Date musteriTarih;
     private Integer musteriPuan;
     private Set kiraharekets = new HashSet(0);
     private Set satisgecmises = new HashSet(0);

    public Musteri() {
    }

	
    public Musteri(long musteriTc, String musteriAd, String musteriSoyad, String musteriMail, long musteriTel, String musteriAdres, Date musteriTarih) {
        this.musteriTc = musteriTc;
        this.musteriAd = musteriAd;
        this.musteriSoyad = musteriSoyad;
        this.musteriMail = musteriMail;
        this.musteriTel = musteriTel;
        this.musteriAdres = musteriAdres;
        this.musteriTarih = musteriTarih;
    }
    public Musteri(long musteriTc, String musteriAd, String musteriSoyad, String musteriMail, long musteriTel, String musteriAdres, Date musteriTarih, Integer musteriPuan, Set kiraharekets, Set satisgecmises) {
       this.musteriTc = musteriTc;
       this.musteriAd = musteriAd;
       this.musteriSoyad = musteriSoyad;
       this.musteriMail = musteriMail;
       this.musteriTel = musteriTel;
       this.musteriAdres = musteriAdres;
       this.musteriTarih = musteriTarih;
       this.musteriPuan = musteriPuan;
       this.kiraharekets = kiraharekets;
       this.satisgecmises = satisgecmises;
    }
   
    public Integer getMusteriId() {
        return this.musteriId;
    }
    
    public void setMusteriId(Integer musteriId) {
        this.musteriId = musteriId;
    }
    public long getMusteriTc() {
        return this.musteriTc;
    }
    
    public void setMusteriTc(long musteriTc) {
        this.musteriTc = musteriTc;
    }
    public String getMusteriAd() {
        return this.musteriAd;
    }
    
    public void setMusteriAd(String musteriAd) {
        this.musteriAd = musteriAd;
    }
    public String getMusteriSoyad() {
        return this.musteriSoyad;
    }
    
    public void setMusteriSoyad(String musteriSoyad) {
        this.musteriSoyad = musteriSoyad;
    }
    public String getMusteriMail() {
        return this.musteriMail;
    }
    
    public void setMusteriMail(String musteriMail) {
        this.musteriMail = musteriMail;
    }
    public long getMusteriTel() {
        return this.musteriTel;
    }
    
    public void setMusteriTel(long musteriTel) {
        this.musteriTel = musteriTel;
    }
    public String getMusteriAdres() {
        return this.musteriAdres;
    }
    
    public void setMusteriAdres(String musteriAdres) {
        this.musteriAdres = musteriAdres;
    }
    public Date getMusteriTarih() {
        return this.musteriTarih;
    }
    
    public void setMusteriTarih(Date musteriTarih) {
        this.musteriTarih = musteriTarih;
    }
    public Integer getMusteriPuan() {
        return this.musteriPuan;
    }
    
    public void setMusteriPuan(Integer musteriPuan) {
        this.musteriPuan = musteriPuan;
    }
    public Set getKiraharekets() {
        return this.kiraharekets;
    }
    
    public void setKiraharekets(Set kiraharekets) {
        this.kiraharekets = kiraharekets;
    }
    public Set getSatisgecmises() {
        return this.satisgecmises;
    }
    
    public void setSatisgecmises(Set satisgecmises) {
        this.satisgecmises = satisgecmises;
    }




}


