package model.POJO;
// Generated 24.Ara.2014 00:38:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Satisgecmis generated by hbm2java
 */
public class Satisgecmis  implements java.io.Serializable {


     private Integer satisGesmisId;
     private Musteri musteri;
     private Urun urun;
     private String durum;
     private Date satisKiraTarih;
     private int satisFiyat;
     
     private int ID;
     private String Urunler;
     private String Musteriler;

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getUrunler() {
        return Urunler;
    }

    public void setUrunler(String Urunler) {
        this.Urunler = Urunler;
    }

    public String getMusteriler() {
        return Musteriler;
    }

    public void setMusteriler(String Musteriler) {
        this.Musteriler = Musteriler;
    }

    public Satisgecmis() {
    }

    public Satisgecmis(Musteri musteri, Urun urun, String durum, Date satisKiraTarih, int satisFiyat) {
       this.musteri = musteri;
       this.urun = urun;
       this.durum = durum;
       this.satisKiraTarih = satisKiraTarih;
       this.satisFiyat = satisFiyat;
    }
   
    public Integer getSatisGesmisId() {
        return this.satisGesmisId;
    }
    
    public void setSatisGesmisId(Integer satisGesmisId) {
        this.satisGesmisId = satisGesmisId;
    }
    public Musteri getMusteri() {
        return this.musteri;
    }
    
    public void setMusteri(Musteri musteri) {
        this.musteri = musteri;
    }
    public Urun getUrun() {
        return this.urun;
    }
    
    public void setUrun(Urun urun) {
        this.urun = urun;
    }
    public String getDurum() {
        return this.durum;
    }
    
    public void setDurum(String durum) {
        this.durum = durum;
    }
    public Date getSatisKiraTarih() {
        return this.satisKiraTarih;
    }
    
    public void setSatisKiraTarih(Date satisKiraTarih) {
        this.satisKiraTarih = satisKiraTarih;
    }
    public int getSatisFiyat() {
        return this.satisFiyat;
    }
    
    public void setSatisFiyat(int satisFiyat) {
        this.satisFiyat = satisFiyat;
    }






}


