package model.POJO;
// Generated 02.Oca.2015 16:58:18 by Hibernate Tools 4.3.1



/**
 * Sepet generated by hbm2java
 */
public class Sepet  implements java.io.Serializable {


     private Integer sepetId;
     private Urun urun;

    public Sepet() {
    }

    public Sepet(Urun urun) {
       this.urun = urun;
    }
   
    public Integer getSepetId() {
        return this.sepetId;
    }
    
    public void setSepetId(Integer sepetId) {
        this.sepetId = sepetId;
    }
    public Urun getUrun() {
        return this.urun;
    }
    
    public void setUrun(Urun urun) {
        this.urun = urun;
    }




}


