package model.POJO;
// Generated 02.Oca.2015 16:58:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Silinenmusteri generated by hbm2java
 */
public class Silinenmusteri  implements java.io.Serializable {


     private Integer smusteriId;
     private long smusteriTc;
     private String smusteriAd;
     private String smusteriSoyad;
     private String smusteriMail;
     private long smusteriTel;
     private String smusteriAdres;
     private Date smusteriTarih;
     private int smusteriPuan;

    public Silinenmusteri() {
    }

    public Silinenmusteri(long smusteriTc, String smusteriAd, String smusteriSoyad, String smusteriMail, long smusteriTel, String smusteriAdres, Date smusteriTarih, int smusteriPuan) {
       this.smusteriTc = smusteriTc;
       this.smusteriAd = smusteriAd;
       this.smusteriSoyad = smusteriSoyad;
       this.smusteriMail = smusteriMail;
       this.smusteriTel = smusteriTel;
       this.smusteriAdres = smusteriAdres;
       this.smusteriTarih = smusteriTarih;
       this.smusteriPuan = smusteriPuan;
    }
   
    public Integer getSmusteriId() {
        return this.smusteriId;
    }
    
    public void setSmusteriId(Integer smusteriId) {
        this.smusteriId = smusteriId;
    }
    public long getSmusteriTc() {
        return this.smusteriTc;
    }
    
    public void setSmusteriTc(long smusteriTc) {
        this.smusteriTc = smusteriTc;
    }
    public String getSmusteriAd() {
        return this.smusteriAd;
    }
    
    public void setSmusteriAd(String smusteriAd) {
        this.smusteriAd = smusteriAd;
    }
    public String getSmusteriSoyad() {
        return this.smusteriSoyad;
    }
    
    public void setSmusteriSoyad(String smusteriSoyad) {
        this.smusteriSoyad = smusteriSoyad;
    }
    public String getSmusteriMail() {
        return this.smusteriMail;
    }
    
    public void setSmusteriMail(String smusteriMail) {
        this.smusteriMail = smusteriMail;
    }
    public long getSmusteriTel() {
        return this.smusteriTel;
    }
    
    public void setSmusteriTel(long smusteriTel) {
        this.smusteriTel = smusteriTel;
    }
    public String getSmusteriAdres() {
        return this.smusteriAdres;
    }
    
    public void setSmusteriAdres(String smusteriAdres) {
        this.smusteriAdres = smusteriAdres;
    }
    public Date getSmusteriTarih() {
        return this.smusteriTarih;
    }
    
    public void setSmusteriTarih(Date smusteriTarih) {
        this.smusteriTarih = smusteriTarih;
    }
    public int getSmusteriPuan() {
        return this.smusteriPuan;
    }
    
    public void setSmusteriPuan(int smusteriPuan) {
        this.smusteriPuan = smusteriPuan;
    }




}


