package model.POJO;
// Generated 02.Oca.2015 16:58:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String userPassword;
     private String userMail;
     private Set desteks = new HashSet(0);

    public User() {
    }

	
    public User(String userName, String userPassword, String userMail) {
        this.userName = userName;
        this.userPassword = userPassword;
        this.userMail = userMail;
    }
    public User(String userName, String userPassword, String userMail, Set desteks) {
       this.userName = userName;
       this.userPassword = userPassword;
       this.userMail = userMail;
       this.desteks = desteks;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserMail() {
        return this.userMail;
    }
    
    public void setUserMail(String userMail) {
        this.userMail = userMail;
    }
    public Set getDesteks() {
        return this.desteks;
    }
    
    public void setDesteks(Set desteks) {
        this.desteks = desteks;
    }




}


